README.md

Minor readme fix to reflect the actual client parameters required during initialization

docs: add proper client parameters

---

CHANGELOG.md
influxdb3/query_iterator.go
influxdb3/query_iterator_test.go

fix for bug if reader.Next returns an empty result. 
Now it results in panic:
```
panic: runtime error: index out of range [0] with length 0
goroutine 424 [running]:
github.com/apache/arrow/go/v12/arrow/array.(*String).Value(...)
/go/pkg/mod/github.com/apache/arrow/go/v12@v12.0.0/arrow/array/string.go:54
github.com/InfluxCommunity/influxdb3-go/influx.getArrowValue({0x18e4ed0, 0xc000e44aa0}, 0x0)
/go/pkg/mod/github.com/!influx!community/influxdb3-go@v0.1.0/influx/query_iterator.go:139 +0x1085
github.com/InfluxCommunity/influxdb3-go/influx.(*QueryIterator).Next(0xc000aa62c0)
/go/pkg/mod/github.com/!influx!community/influxdb3-go@v0.1.0/influx/query_iterator.go:62 +0x205
```

fix: no panic if i.reader.Next() returns an empty result

---

CHANGELOG.md
influxdb3/options.go
influxdb3/point.go
influxdb3/write.go
influxdb3/write_test.go

Closes #
While doing exploratory testing of the library, I discovered I could not access `defaultTags` in my local project.  
This changes the naming of `defaultTags` in `WriteOptions` to `DefaultTags` to make the field visible outside of the package.

fix: exports DefaultTags from package

---

.circleci/config.yml
influxdb3/client_e2e_test.go

Changes CircleCI job not to run e2e tests on PRs from forks. `CIRCLE_BRANCH` env var is set to `pull/NUMBER` when run for fork PR: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/

chore: do not run e2e on PRs from forks

---

CHANGELOG.md
influxdb3/config.go
influxdb3/point_values.go

Closes #73
_Briefly describe your proposed changes:_
Added log package to solve issue https://github.com/InfluxCommunity/influxdb3-go/issues/73

feat: Added logging

---

CHANGELOG.md
influxdb3/options.go
influxdb3/query_type.go

Closes #70
Rename `FlightSQL` constant to `SQL`.

refactor: rename `FlightSQL` constant to `SQL`

---

CHANGELOG.md
influxdb3/client.go
influxdb3/client_e2e_test.go
influxdb3/example_query_test.go
influxdb3/options.go
influxdb3/options_test.go
influxdb3/query.go
influxdb3/query_test.go

* Adds custom headers (from either `ClientConfig` and/or provided to query via `WithHeader` options)  to a gRPC query request.
* Query call examples are now in "godoc" style - compilable (but not executed during `go test`) code in `example_query_test.go`, from which documentation examples are generated and linked with functions and types on `pkg.go.dev` portal, see #78

feat: add support for custom query/gRPC headers

---

CHANGELOG.md
influxdb3/query.go
influxdb3/query_test.go
influxdb3/write.go

* Sets `user-agent` header in metadata for query calls by default
* Adds test for default headers in query calls
* Cleans up a couple of lines in writer that linter complained about locally

feat: user-agent header in gRPC

---

CHANGELOG.md
influxdb3/client.go
influxdb3/client_test.go
influxdb3/config.go

Closes #88
_Briefly describe your proposed changes:_
Refactored #88, based on my comments there:
*  does not modify client-provided `config` instance (by setting fallback value to unset property)
* renamed property `TokenPrefix` -> `AuthScheme` per terminology used eg. in https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization
* `AuthScheme` also supported in Client init from connection string and/or environment variables

feat: Edge authentication

---

.circleci/config.yml
.golangci.yml
CHANGELOG.md
influxdb3/example_query_test.go
influxdb3/query_test.go

Related to #94 
Add https://golangci-lint.run to our CI.

chore: add `golangci-lint` to CI

---

.circleci/config.yml
.golangci.yml
CHANGELOG.md
influxdb3/management_cloud_decicated.go
influxdb3/management_serverless.go
influxdb3/write.go

When the returned `Response`'s body is `nil`, the caller of the function is expected to `Close` the body. If this is not done, it can lead to a resource leak.
[Ref](https://pkg.go.dev/net/http#Client.Do)
>If the returned error is nil, the Response will contain a non-nil Body which the user is expected to close.
This is also caught by a `golangci-lint` check of `bodyclose`, e.g. running from `main`:
```bash
git branch --show-current
main
golangci-lint run --enable-only bodyclose
influxdb3/management_cloud_decicated.go:146:31: response body must be closed (bodyclose)
_, err = d.client.makeAPICall(ctx, param)
^
influxdb3/management_serverless.go:98:31: response body must be closed (bodyclose)
_, err = c.client.makeAPICall(ctx, param)
^
influxdb3/write.go:168:24: response body must be closed …
```

fix: unclosed body causing resource leak

---

influxdb3/client_e2e_test.go

The "SHOW NAMESPACES" is not allowed to use. The tests was failing with:
```
--- FAIL: TestQuerySchemaWithOptions (0.47s)
client_e2e_test.go:266: 
Error Trace:    /Users/bednar/Developer/InfluxData/influxdb3-go/influxdb3/client_e2e_test.go:266
Error:          Received unexpected error:
flight reader: rpc error: code = InvalidArgument desc = Error while planning query: Error during planning: 'namespaces' is not a variable which can be viewed with 'SHOW'
Test:           TestQuerySchemaWithOptions
```
https://app.circleci.com/pipelines/github/InfluxCommunity/influxdb3-go/347/workflows/c1980310-4c9e-4757-83ca-f3833517be47/jobs/371

fix: e2e tests

---

CHANGELOG.md
influxdb3/management_cloud_decicated.go
influxdb3/management_cloud_dedicated_test.go

Cloud Dedicated database creation ignores the database name given by an argument, but applies the database name within client configuration. This behavior differs from the API spec and user intuitions, so I'd say it's a bug.

fix: CloudDedicated database creation ignores the given name

---

CHANGELOG.md
examples/General/httpErrorHandled.go
influxdb3/client.go
influxdb3/client_e2e_test.go
influxdb3/error.go
influxdb3/example_write_test.go
influxdb3/write_test.go

- Add `http.Header` to `ServerError`
- Add tests of this change
- Add examples of accessing response headers on write fail.

feat: expose http response headers in ServerError

---

CHANGELOG.md
influxdb3/write.go
influxdb3/write_test.go

Hello I am testing ``influxdb3`` to host my timeseries data. 
I am interacting with the DB using this library. I have one ``influxdb`` client shared among my ``go`` routines.  
I am regularely receiving errors of this kind when attempting to write data:
`http2: Transport: cannot retry err [http2: Transport received Server's graceful shutdown GOAWAY] after Request.Body was written; define Request.GetBody to avoid this error`
I noticed that the library does not allow for ``Request.Body`` to be set when gzipping is enabled. 
This change works around this to allow for more resilient client calls against influxdb3's HTTP/2 server.

feature: allow Request.GetBody to be set when gzipping

---

CHANGELOG.md
influxdb3/client_e2e_test.go
influxdb3/point.go
influxdb3/point_test.go

Related https://github.com/influxdata/EAR/issues/5476#issuecomment-2417071571
- In `point.MarshallBinaryWithDefaultTags` add a mapping of strings to be escaped. 
- In same method add an internal method for iterating over map and escaping values in source string
- Rename `TestPointWithNewLineTags` to `TestPointWithEscapedTags`
- Add check in this and in `client_e2e_test` of tab (i.e. `\t`) escapes in tags.

feat: escape tabs in tag strings

---

CHANGELOG.md
README.md
examples/Basic/basic.go
examples/Batching/batching.go
examples/Downsampling/downsampling.go
examples/HTTPErrorHandled/httpErrorHandled.go
examples/LPBatching/lpBatching.go
examples/README.md
go.mod
influxdb3/batching/batcher.go
influxdb3/batching/batcher_test.go
influxdb3/batching/example_test.go
influxdb3/client_e2e_test.go
influxdb3/query.go
influxdb3/query_iterator.go
influxdb3/version.go
influxdb3/write.go

Closes https://github.com/influxdata/EAR/issues/5646
1/ This PR changed how we parse response from InfluxDB, now we respect the `iox::column_type::field` metadata.
2/ Enhance documentation for Query API.

feat: respect `iox::column_type::field` metadata when mapping query results into values

---

CHANGELOG.md
README.md
examples/Basic/basic.go
examples/Batching/batching.go
examples/Downsampling/downsampling.go
examples/HTTPErrorHandled/httpErrorHandled.go
examples/LPBatching/lpBatching.go
go.mod
influxdb3/batching/batcher.go
influxdb3/batching/batcher_test.go
influxdb3/batching/example_test.go
influxdb3/client_e2e_test.go
influxdb3/write.go

The last major release v1.0.0 with module suffix /v1 can not be used. We have to update to v2

chore: prepare v2

---

influxdb3/batching/lp_batcher.go
influxdb3/batching/lp_batcher_test.go

Motivated by EAR 5762
In `LPBatcher.emitBytes()`
* Check whether the first line exceeds the buffer size.
* If it does, just emit the first line and adjust the buffer accordingly
* If not, proceed with emitting the packet and correct the buffer as before

fix: LPBatcher issue - lines longer than the buffer size lead to emitting 0 size packets and unemptied buffer

---

CHANGELOG.md
go.mod

Closes #133 
Drop "minimum virus" which comes from grpc-go ... for more info see #133.

fix: remove unnecessary toolchain includes and set the minimum Go version to 1.22

---

CHANGELOG.md
README.md
examples/Basic/basic.go
influxdb3/client.go
influxdb3/client_test.go
influxdb3/config.go
influxdb3/example_query_test.go
influxdb3/example_test.go
influxdb3/options.go
influxdb3/write_test.go

Closes https://github.com/InfluxCommunity/influxdb3-go/issues/144
InfluxDB 3 Go client uses a wrapped `http.Client` for **write** operations (for queries GRPC client is used). This `http.Client` supports connection pooling but unfortunately the used default configuration is unacceptable for production use. This PR focuses on the main configuration issues of this HTTP client.
- Fixing the following issues of the wrapped `http.Client`:
- default `Timeout` was set to unlimited, so if a connection was pending then the client was waiting forever
- default `MaxIdleConnsPerHost` was set to `2` which highly limited the connection reuse
- Introduced new configuration options to configure the wrapped `http.Client`:
- `Timeout` - sets `Timeout`, default: `10s`
- `IdleConnectionTimeout` - sets …

feat: configurable http client

---

CHANGELOG.md
influxdb3/point_value_iterator.go
influxdb3/point_value_iterator_test.go
influxdb3/query.go
influxdb3/query_iterator.go
influxdb3/query_iterator_test.go

Closes https://github.com/InfluxCommunity/influxdb3-go/issues/145
Export functions `NewQueryIterator` and `NewPointValueIterator` to simplify testing.

feat: export NewQueryIterator and NewPointValueIterator

---

CHANGELOG.md
influxdb3/batching/batcher.go
influxdb3/batching/lp_batcher.go
influxdb3/client.go
influxdb3/testutil/mocks.go

Closes #
* Change the slog warnings for Batcher and LPBatcher, when buffer data can't be automatically emitted to DEBUG. 
* Reorder functions for Batcher, LPBatcher, Client and MockFlightServer to satisfy new linter requirements.

chore: change Batcher slog warnings to level DEBUG

---

CHANGELOG.md
influxdb3/batching/batcher.go
influxdb3/batching/batcher_test.go
influxdb3/batching/lp_batcher.go
influxdb3/batching/lp_batcher_test.go
influxdb3/client_e2e_test.go

Closes #157
* Simplify debug messages when batcher buffer data is not being emitted.
* Rename Batcher methods and fields from `xCapacity` to `xInitialCapacity`
* Mark Batcher methods using `xCapacity` as deprecated

fix: issue157

---

CHANGELOG.md
influxdb3/client.go
influxdb3/client_test.go
influxdb3/config.go
influxdb3/management_serverless.go
influxdb3/options.go
influxdb3/options_test.go
influxdb3/write.go
influxdb3/write_test.go

Support fast writes without waiting for WAL persistence:
- New write option (`WriteOptions.NoSync`) added: `true` value means faster write but without the confirmation that
the data was persisted. Default value: `false`.
- **Supported by self-managed InfluxDB 3 Core and Enterprise servers only!**
- Also configurable via connection string query parameter (`writeNoSync`).
- Also configurable via environment variable (`INFLUX_WRITE_NO_SYNC`).
- Long precision string values added from v3 HTTP API: `"nanosecond"`, `"microsecond"`, `"millisecond"`, `"second"` (in addition to the existing `"ns"`, `"us"`, `"ms"`, `"s"`).

feat: fast no-sync write support

---

.golangci.yml
CHANGELOG.md
influxdb3/point.go
influxdb3/point_test.go

Closes [#160 ](https://github.com/InfluxCommunity/influxdb3-go/issues/160)
- Support type conversion for named type. Currently named types will be converted to a string.
- I can't find any alternative way, so I have to use reflection api even though it's slow.

feat: convert named type

---

.golangci.yml

Closes [#864](https://github.com/influxdata/edge/issues/864)
- I have checked in here [Link](https://golangci-lint.run/usage/linters/#disabled-by-default) and these new linter rules are disabled by default so I think we just following the same.
- The disable has been done in another PR so this PR is just for remove the comment in the .golangci.yml file

feat: disable linter rules

---

.golangci.yml
CHANGELOG.md
influxdb3/point.go
influxdb3/point_values.go

Closes #
- Add comments to warn user that getMeasurement() function will return null when querying with SQL Query.
- Reference [Link](https://github.com/influxdata/influxdb/issues/26603).
- Disable linter for `noctx` rule base on default rules [Default rules](https://golangci-lint.run/usage/linters/#:~:text=v1.30.0-,noctx%C2%A0Detects%20function%20and%20method%20with%20missing%20usage%20of%20context.Context.,-v1.28.0)

feat: add comment for getMeasurement function

---

examples/Basic/basic.go

`examples/Basic/basic.go` now features up-to-date timeout parameters and no longer uses deprecated parameter `Timeout`.  
Rebased with force

docs: update basic example with newer timeout parameters.
